version: '3'
services:
  app:
    build:
      context: ./back
    ports:
      - "3000:3000"
    container_name: app
    volumes:
      - ./back/:/app
      - /app/node_modules
    environment:
      - PORT=3000
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    container_name: web
    stdin_open: true
    volumes:
       - ./web:/web
       - /web/node_modules
