version: '3'
services:
  app:
    build:
      context: ./back
      args:
        NODE_ENV: development
    volumes:
      - ./back/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev